const keywords = {
    "health": [
        "METTLESOME", 
        "PEACEFUL", 
        "HEALTHY", 
        "VIGOROUS", 
        "GREEN", 
        "VIBRANT", 
        "ABLE-BODIED", 
        "FORCEFUL", 
        "HAPPY", 
        "Energetic",
        "breezy",
        "talkative",
        "TENDER"
    ],
    "love": [
        "INDEPENDENT",
        "RELIABLE",
        "LOYAL",
        "ROMANTIC",
        "STEADY",
        "FRESH",
        "RATIONAL",
        "TENDER",
        "faithful",
        "CLINGY",
        "fearless",
        "FLIRTING",
        "STRICT",
        "SOBER",
        "LIBERTINE",
        "NOSTALGIC",
        "NAIVE",
        "EMOTIONAL",
        "easy-going",
        "affectionate"
    ],
    "career": [
        "PASSIONATE", 
        "CONFIDENT", 
        "COOL-HEADED ",
        "STEADY", 
        "PRAGMATIC", 
        "SENTIMENTAL", 
        "PERFECT", 
        "IRRESOLUTE", 
        "INTREPID", 
        "OPTIMISTIC", 
        "PERSISTENT", 
        "reflective",
        "Self-starter",
        "EMULATIVE",
        "IMPRUDENT",
        "DILIGENT",
        "HARMONIOUS",
        "DECISIVE",
        "friendly",
        "Reactive",
        "Tactful",
    ],
    "money": [
        "GENEROUS", 
        "LUXURIOUS", 
        "LOW-KEY", 
        "ENJOYABLE", 
        "COMFORTABLE", 
        "SECURE", 
        "OPTIMISTIC", 
        "INTELLIGENT", 
        "steady",
        "FRUGAL",
        "practical",
        "Refinement",
        "TENSE",
        "good taste",
        "Seeks higher",
        "windfall"
    ]
};

export default keywords;